package org.example.cereri;

public enum TipCerereEnum {
    INLOCUIRE_BULETIN,
    INREGISTRARE_VENIT_SALARIAL,
    INLOCUIRE_CARNET_DE_SOFER,
    INLOCUIRE_CARNET_DE_ELEV,
    CREARE_ACT_CONSTITUTIV,
    REINNOIRE_AUTORIZATIE,
    INREGISTRARE_CUPOANE_DE_PENSIE,
}